### ISSUE TITLE
Can't run base code

### ISSUE THREAD

**Issue by jddanna** [devkotasabin/SPX-graph-layout#1]
After installing dependencies and running `python spx.py` I get the following error message:

Traceback (most recent call last):
  File "spx.py", line 241, in <module>
    plotGraphandStats(X_curr)
  File "spx.py", line 97, in plotGraphandStats
    A,B = getEdgePairAsMatrix(X,i,j)
  File "spx.py", line 62, in getEdgePairAsMatrix
    i1, i2 = getNodesforEdge(i)
  File "spx.py", line 51, in getNodesforEdge
    return edge_list[index][0], edge_list[index][1]
  File "...\reportviews.py", line 1015, in __getitem__
    u, v = e
TypeError: 'int' object is not iterable

Any ideas on what the problem could be? I tried running the code on Python 3.6 and then Python 3.8 because PyGraphViz had listed 3.7 to be the minimum version. Also, I ended up having to refactor some of the print statements to run because they hadn't contained parentheses (Python 3 requires parentheses for print statements while Python 2 did not). Should the code be run on Python 2 or 3?

**Comment by devkotasabin** [comment]
Hi jddanna,Sorry for the late reply. I am not currently maintaining the
project. You can contact Abu Reyan Ahmed at
***@***.*** about
the codebase. Thank you.

Regards,
Sabin Devkota
